---
- name: Check {{ direct_binary.name }}
  ansible.builtin.command: "which {{ direct_binary.name }}"
  register: direct_binary_check
  changed_when: false
  failed_when: false

- name: Download and install {{ direct_binary.name }}
  become: true
  ansible.builtin.get_url:
    url: "{{ direct_binary.url }}"
    dest: "/usr/local/bin/{{ direct_binary.name }}"
    mode: "0755"
  when: direct_binary_check.rc != 0
